Dict(
    # Page title and optional disclaimer for the homepage
    "title" => "Quantum Computing",
    "disclaimer" => "",
    
    # Jumbotron Carousel - Featured highlights displayed separately
    "carousel" => [
        Dict("name" => "Easy to customise", 
             "text" => md"Let the template automate all of the website development and infrastructure, so that you can focus on the most important thing:
             **easily develop your lesson materials!**",
             "img" => "https://user-images.githubusercontent.com/6933510/168320383-a401459b-97f5-41df-bc7b-ebe76e4886cc.png"
        ),
        Dict("name" => "Revolutionary interactivity with Pluto.jl",
             "text" => md"""
             Thanks to Pluto.jl, the website is built using real code, and instead of a book, we have a series of interactive notebooks.
             **On the website, students can play with sliders, buttons and images to interact with our simulations.**
             You can even go further, and modify and run any code on our website!
             """,
             "img" => "https://user-images.githubusercontent.com/6933510/136196607-16207911-53be-4abb-b90e-d46c946e6aaf.gif"
             ),
        Dict("name" => "Learn Julia",
             "text" => md"""
             In literature it's not enough to just know the technicalities of grammar.
             In music it's not enough to learn the scales. The goal is to communicate experiences and emotions.
             For a computer scientist, it's not enough to write a working program,
             the program should be written with beautiful high level abstractions that speak to your audience.
             **Julia is designed with this purpose in mind, use it in your teaching to harness its power.**
             """,
             "img" => "https://user-images.githubusercontent.com/6933510/136203632-29ce0a96-5a34-46ad-a996-de55b3bcd380.png"
             )    
    ],
    
    # References section 
    "references" => [
        Dict("name" => "Genie",
             "url" => "https://genie.julialang.org/",
             "description" => "A full-stack web framework for Julia. Genie makes it easy to build modern web applications with Julia.",
             "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
             "category" => "Core Quantum Platforms"
        ),
        Dict("name" => "Q# IOT Project",
             "url" => "https://github.com/jlabclouds/qsharpIoT",
             "description" => "A practical project that integrates Q# with IoT devices. Learn how to connect quantum computing concepts with real-world applications in the Internet of Things (IoT) domain.",
             "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
             "category" => "Core Quantum Platforms"
        ), 
        Dict("name" => "QuTiP: Quantum Toolbox in Python",
             "url" => "http://qutip.org/",
             "description" => "QuTiP is an open-source software for simulating the dynamics of quantum systems. It provides a comprehensive set of tools for quantum mechanics, quantum optics, and quantum information processing. QuTiP is widely used in research and education for modeling and analyzing quantum systems, making it an essential resource for anyone interested in quantum computing and quantum physics.",
             "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
             "category" => "Core Quantum Platforms"
        ),
    ],

    # Resources section - Quantum Providers and Tools with Dropdowns
    "resources" => [
        Dict("name" => "Quantum Providers",
             "emoji" => "🏥",
             "gradient_from" => "#f5f7fa",
             "gradient_to" => "#c3cfe2",
             "description" => "Advanced quantum computing platforms providing access to quantum hardware, simulators, and development tools for quantum algorithm development.",
             "select_placeholder" => "Choose a Provider",
             "options" => [
                Dict("key" => "azure", "name" => "Microsoft: Azure Quantum",
                     "url" => "https://azure.microsoft.com/en-us/services/quantum/",
                     "description" => "Microsoft's Azure Quantum platform offers access to quantum hardware, software tools, and resources.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Core Quantum Platforms",
                     "related_tools" => [
                        Dict("name" => "Q#", "url" => "https://learn.microsoft.com/en-us/azure/quantum/overview-what-is-qsharp", "description" => "Microsoft's Q# quantum programming language"),
                        Dict("name" => "QIR", "url" => "https://learn.microsoft.com/en-us/azure/quantum/concepts-qir", "description" => "Quantum Intermediate Representation for cross-platform quantum programs"),
                        Dict("name" => "Nuget F#", "url" => "https://www.nuget.org/packages/FSharp.Azure.Quantum#c-fluent-api", "description" => "NuGet package for F# Azure Quantum development. Provides tools and libraries for building quantum applications using F# on the Azure Quantum platform.")
                     ]),
                Dict("key" => "quantinuum", "name" => "Honeywell: Quantinuum Nexus",
                     "url" => "https://docs.quantinuum.com/nexus/index.html",
                     "description" => "Quantinuum's Nexus platform documentation and resources.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Core Quantum Platforms",
                     "related_tools" => [
                        Dict("name" => "Guppy", "url" => "https://docs.quantinuum.com/guppy/getting_started.html", "description" => "Quantum programming language by Quantinuum")
                     ]),
                Dict("key" => "ibm", "name" => "IBM Quantum: Qiskit",
                     "url" => "https://www.ibm.com/quantum/",
                     "description" => "Access IBM's quantum processors and simulators through the cloud.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Core Quantum Platforms",
                     "related_tools" => [
                        Dict("name" => "Qiskit", "url" => "https://qiskit.org/", "description" => "IBM's open-source Python framework for quantum computing"),
                        Dict("name" => "Qiskit Machine Learning", "url" => "https://qiskit-machine-learning.readthedocs.io/", "description" => "Quantum machine learning module for Qiskit"),
                        Dict("name" => "IBM Quantum Composer", "url" => "https://quantum-computing.ibm.com/composer", "description" => "Visual tool for designing and simulating quantum circuits")
                     ]),
                Dict("key" => "google", "name" => "Google Quantum AI: Cirq & Sycamore",
                     "url" => "https://quantumai.google/",
                     "description" => "Explore Google's quantum computing initiatives and resources.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Core Quantum Platforms",
                     "related_tools" => [
                        Dict("name" => "Cirq", "url" => "https://quantumai.google/cirq", "description" => "Python framework for designing quantum circuits and algorithms"),
                        Dict("name" => "TensorFlow Quantum", "url" => "https://www.tensorflow.org/quantum", "description" => "Quantum machine learning library built on TensorFlow")
                     ]),
                Dict("key" => "braket", "name" => "Amazon: Braket",
                     "url" => "https://aws.amazon.com/braket/",
                     "description" => "Amazon Braket is a fully managed quantum computing service.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Core Quantum Platforms"),
                Dict("key" => "rigetti", "name" => "Rigetti: Forest",
                     "url" => "https://www.rigetti.com/forest",
                     "description" => "Rigetti's Forest platform documentation and resources.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Core Quantum Platforms",
                     "related_tools" => [
                        Dict("name" => "Quil", "url" => "https://rigetti.com/qcs", "description" => "Quantum Instruction Language for programming Rigetti quantum processors")
                     ]),
                Dict("key" => "ionq", "name" => "IonQ: Quantum Cloud",
                     "url" => "https://ionq.com/quantum-cloud",
                     "description" => "IonQ's Quantum Cloud documentation and resources.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Core Quantum Platforms"),
                Dict("key" => "dwave", "name" => "D-Wave: Quantum Annealing",
                     "url" => "https://www.dwavesys.com/quantum-computing/quantum-annealing",
                     "description" => "D-Wave's quantum annealing platform documentation.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Core Quantum Platforms",
                     "related_tools" => [
                        Dict("name" => "D-Wave Documentation", "url" => "https://docs.dwavequantum.com/en/latest/", "description" => "Access D-Wave's quantum annealing resources and documentation")
                     ]),
                Dict("key" => "xanadu", "name" => "Xanadu: Strawberry Fields",
                     "url" => "https://www.xanadu.ai/strawberryfields",
                     "description" => "Xanadu's Strawberry Fields documentation and resources.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Core Quantum Platforms",
                     "related_tools" => [
                        Dict("name" => "PennyLane", "url" => "https://pennylane.ai/", "description" => "Python library for quantum machine learning and differentiable computing")
                     ]),
                Dict("key" => "quantum-inspire", "name" => "Quantum Inspire",
                     "url" => "https://www.quantum-inspire.com/",
                     "description" => "Quantum Inspire is a quantum computing platform developed by QuTech.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Core Quantum Platforms"),
             ]),
        Dict("name" => "Optimization Problems",
             "emoji" => "⚙️",
             "gradient_from" => "#a8edea",
             "gradient_to" => "#fed6e3",
             "description" => "Solving complex optimization challenges in logistics, finance, and resource allocation using QAOA and other quantum optimization algorithms.",
             "select_placeholder" => "Choose a Tool",
             "options" => [
                Dict("key" => "qaoa", "name" => "QAOA: Quantum Approximate Optimization",
                     "url" => "https://qiskit.org/documentation/stable/0.39/tutorials/algorithms/05_qaoa.html",
                     "description" => "Quantum Approximate Optimization Algorithm for solving combinatorial optimization problems on near-term quantum devices.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Optimization Algorithms",
                     "related_tools" => [
                        Dict("name" => "Qiskit QAOA", "url" => "https://qiskit.org/documentation/stable/0.39/stubs/qiskit.algorithms.QAOA.html", "description" => "Qiskit implementation of QAOA"),
                        Dict("name" => "Cirq Optimization", "url" => "https://quantumai.google/cirq/optimize", "description" => "Google Cirq optimization module")
                     ]),
                Dict("key" => "vqe", "name" => "VQE: Variational Quantum Eigensolver",
                     "url" => "https://qiskit.org/documentation/stable/0.39/tutorials/algorithms/04_vqe.html",
                     "description" => "Variational quantum eigensolver for finding ground state energies and solving optimization problems.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Optimization Algorithms",
                     "related_tools" => [
                        Dict("name" => "Qiskit VQE", "url" => "https://qiskit.org/documentation/stable/0.39/stubs/qiskit.algorithms.VQE.html", "description" => "Qiskit VQE algorithm implementation"),
                        Dict("name" => "PennyLane VQE", "url" => "https://pennylane.ai/qml/demos/tutorial_vqe.html", "description" => "VQE with Xanadu's PennyLane framework")
                     ]),
                Dict("key" => "maxcut", "name" => "MaxCut Problem",
                     "url" => "https://github.com/Qiskit/qiskit-machine-learning/blob/main/examples/circuit_classifier.py",
                     "description" => "Maximum Cut problem - a classic NP-hard optimization problem solved with quantum algorithms.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Optimization Applications"),
                Dict("key" => "annealing", "name" => "Quantum Annealing",
                     "url" => "https://www.dwavesys.com/quantum-computing/quantum-annealing",
                     "description" => "Adiabatic quantum computation for solving optimization problems on specialized quantum processors.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Optimization Algorithms",
                     "related_tools" => [
                        Dict("name" => "D-Wave Leap", "url" => "https://cloud.dwavesys.com/", "description" => "D-Wave quantum annealing cloud platform")
                     ]),
                Dict("key" => "algozoo", "name" => "Quantum Algorithm Zoo",
                     "url" => "https://quantumalgorithmzoo.org/",
                     "description" => "A comprehensive collection of quantum algorithms including optimization algorithms categorized by application domain.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Algorithms"),
                Dict("key" => "Algorithm Visualizer", "name" => "Algorithm Visualizer",
                     "url" => "https://algorithm-visualizer.org/",
                     "description" => "Visualize classic algorithms step-by-step. Useful for understanding algorithmic foundations that underpin quantum algorithms.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Interactive Learning & Tools"),
                Dict("key" => "circuitdiagrams", "name" => "Circuit Diagrams",
                     "url" => "https://github.com/microsoft/qdk/wiki/Circuit-Diagrams-from-Q%23-Code/",
                     "description" => "Learn how to visualize quantum circuits from code for optimization algorithms.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Concepts & Visualization"),
             ]),
        Dict("name" => "Robotics Control",
             "emoji" => "🤖",
             "gradient_from" => "#ffecd2",
             "gradient_to" => "#fcb69f",
             "description" => "Quantum-optimized control systems for complex robotic tasks, trajectory optimization, and real-time decision making using quantum advantage.",
             "select_placeholder" => "Choose a Tool",
             "options" => [
                Dict("key" => "ros2", "name" => "ROS 2",
                     "url" => "https://docs.ros.org/en/humble/",
                     "description" => "Robot Operating System 2 - A flexible framework for writing robot software with middleware, tools, and libraries. developed and tested on Ubuntu Linux, making it the recommended operating system",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Robotics Simulation & Control"),
                Dict("key" => "gazebo", "name" => "Gazebo",
                     "url" => "https://gazebosim.org/",
                     "description" => "Gazebo is the industry and academic standard. It features powerful physics engines and is deeply integrated with the ROS ecosystem. If your goal is to map environments or perform complex navigation stacks, and sensor simulation capabilities.Best for ROS/ROS 2 Integration",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Robotics Simulation & Control"),
                Dict("key" => "webots", "name" => "Webots",
                     "url" => "https://cyberbotics.com/",
                     "description" => "Webots - An open-source 3D robot simulator with physics engines and advanced visualization for robotics research.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Robotics Simulation & Control"),
                Dict("key" => "drake", "name" => "Drake",
                     "url" => "https://drake.mit.edu/",
                     "description" => "Drake - A C++ toolbox for modeling and simulation of nonlinear dynamical systems, with applications to robotics.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Robotics Simulation & Control"),
                Dict("key" => "isaac", "name" => "NVIDIA Isaac Sim",
                     "url" => "https://developer.nvidia.com/isaac/sim",
                     "description" => "Isaac Sim is built on the Omniverse platform and offers unparalleled photorealism, making it the top choice for training computer vision models, reinforcement learning, and `sim-to-real` transfers. It utilizes RTX-based rendering to simulate realistic lighting and camera sensor data. Best for AI, Machine Learning, & Vision",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Robotics Simulation & Control"),
                Dict("key" => "mujoco", "name" => "MuJoCo",
                     "url" => "https://mujoco.org/",
                     "description" => "Developed by Google DeepMind, MuJoCo (Multi-Joint dynamics with Contact) is a general-purpose physics engine that is extremely fast and ideal for training legged locomotion, humanoids, and dexterous manipulation algorithms. It is highly optimized and offers GPU-accelerated capabilities through MuJoCo XLA (MJX), with emphasis on contact dynamics and control.Best for Reinforcement Learning.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Robotics Simulation & Control"),
                Dict("key" => "robodk", "name" => "RoboDK",
                     "url" => "https://robodk.com/",
                     "description" => "RoboDK - A robot programming and simulation software that supports multiple robot brands and offline programming. If you are programming 6-axis robotic arms for manufacturing, welding, or pick-and-place, RoboDK allows you to simulate and generate code for over 500 different robot arms without deep programming skills. Best for Industrial Robotics.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Robotics Simulation & Control"),
                Dict("key" => "coppeliasim", "name" => "CoppeliaSim",
                     "url" => "https://www.coppeliarobotics.com/",
                     "description" => "CoppeliaSim (formerly V-REP) is another versatile alternative, featuring distributed control and a massive library of pre-built mechanisms. Best for Industrial Robotics",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Robotics Simulation & Control"),
             ]),
        Dict("name" => "Machine Learning",
             "emoji" => "🧠",
             "gradient_from" => "#ffeaa7",
             "gradient_to" => "#fdcb6e",
             "description" => "Accelerated machine learning pipelines leveraging quantum machine learning techniques for classification, clustering, and pattern recognition.",
             "select_placeholder" => "Choose a Tool",
             "options" => [
                Dict("key" => "qvc", "name" => "Quantum Variational Classifiers",
                     "url" => "https://qiskit.org/documentation/stable/0.39/tutorials/machine_learning/02_neural_networks.html",
                     "description" => "Quantum neural networks for binary and multiclass classification using parameterized quantum circuits.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Machine Learning",
                     "related_tools" => [
                        Dict("name" => "Qiskit Machine Learning", "url" => "https://qiskit-machine-learning.readthedocs.io/", "description" => "IBM's quantum machine learning library"),
                        Dict("name" => "PennyLane QNN", "url" => "https://pennylane.ai/qml/demos/tutorial_qnn.html", "description" => "Quantum neural networks with PennyLane")
                     ]),
                Dict("key" => "qfeaturemap", "name" => "Quantum Feature Maps",
                     "url" => "https://qiskit.org/documentation/stable/0.39/tutorials/machine_learning/01_neural_networks.html",
                     "description" => "Encode classical data into quantum states for enhanced pattern recognition and kernel methods.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Machine Learning",
                     "related_tools" => [
                        Dict("name" => "Qiskit Feature Map", "url" => "https://qiskit.org/documentation/stable/0.39/stubs/qiskit.circuit.library.ZZFeatureMap.html", "description" => "Built-in feature map implementations"),
                        Dict("name" => "PennyLane Templates", "url" => "https://pennylane.ai/qml/template_intro.html", "description" => "PennyLane circuit templates for QML")
                     ]),
                Dict("key" => "qkernel", "name" => "Quantum Kernel Methods",
                     "url" => "https://qiskit.org/documentation/stable/0.39/tutorials/machine_learning/03_quantum_kernel.html",
                     "description" => "Quantum kernel machines for support vector classification and regression in quantum-enhanced feature spaces.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Machine Learning",
                     "related_tools" => [
                        Dict("name" => "Qiskit Quantum Kernel", "url" => "https://qiskit-machine-learning.readthedocs.io/en/stable/stubs/qiskit_machine_learning.kernels.QuantumKernel.html", "description" => "Quantum kernel algorithm implementation"),
                        Dict("name" => "scikit-learn Integration", "url" => "https://scikit-learn.org/", "description" => "Classical ML library for kernel methods")
                     ]),
                Dict("key" => "qautoencoder", "name" => "Quantum Autoencoders",
                     "url" => "https://qiskit.org/documentation/stable/0.39/tutorials/machine_learning/04_qgan.html",
                     "description" => "Learn efficient quantum data compression and dimensionality reduction using hybrid quantum-classical autoencoders.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Machine Learning"),
                Dict("key" => "grover", "name" => "Grover's Search Algorithm",
                     "url" => "https://qiskit.org/documentation/stable/0.39/tutorials/algorithms/03_grover.html",
                     "description" => "Quantum search algorithm for database search and machine learning pattern matching tasks.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Algorithms",
                     "related_tools" => [
                        Dict("name" => "Qiskit Grover", "url" => "https://qiskit.org/documentation/stable/0.39/stubs/qiskit.algorithms.Grover.html", "description" => "Grover algorithm implementation")
                     ]),
                Dict("key" => "qgan", "name" => "Quantum Generative Adversarial Networks",
                     "url" => "https://qiskit.org/documentation/stable/0.39/tutorials/machine_learning/04_qgan.html",
                     "description" => "Hybrid quantum-classical GANs for data generation and quantum state learning.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Machine Learning"),
                Dict("key" => "circuitdiagrams", "name" => "Circuit Diagrams",
                     "url" => "https://github.com/microsoft/qdk/wiki/Circuit-Diagrams-from-Q%23-Code/",
                     "description" => "Learn how to visualize quantum circuits from code for machine learning applications.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Quantum Concepts & Visualization"),
             ]),
        Dict("name" => "Medical Imaging",
             "emoji" => "🏥",
             "gradient_from" => "#ffecd2",
             "gradient_to" => "#fcb69f",
             "description" => "Advanced quantum algorithms for enhanced diagnostic imaging, pattern recognition in medical data, and predictive health analytics using quantum-classical hybrid approaches.",
             "select_placeholder" => "Choose a Tool",
             "options" => [
                Dict("key" => "NIfTI", "name" => "NIfTI",
                     "url" => "https://nifti.nimh.nih.gov/",
                     "description" => "NIfTI (Neuroimaging Informatics Technology Initiative) is a widely used file format for storing and sharing medical imaging data, particularly in neuroimaging research. It provides a standardized way to represent and organize complex imaging datasets, facilitating interoperability and data exchange among researchers and clinicians.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Medical Imaging"),
                Dict("key" => "DICOM", "name" => "DICOM",
                     "url" => "https://www.dicomstandard.org/",
                     "description" => "DICOM (Digital Imaging and Communications in Medicine) is the international standard for handling, storing, and transmitting medical imaging information. It defines a file format and communication protocol for medical images, enabling interoperability between different imaging devices and healthcare systems.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Medical Imaging",
                     "related_tools" => [
                        Dict("name" => "Orthanc", "url" => "https://www.orthanc-server.com/", "description" => "Orthanc is an open-source DICOM server for medical imaging data management and processing."),
                        Dict("name" => "pydicom", "url" => "https://pydicom.github.io/", "description" => "pydicom is a Python library for working with DICOM files, allowing you to read, modify, and write DICOM data in your applications."),
                        Dict("name" => "DICOMweb", "url" => "https://www.dicomstandard.org/dicomweb", "description" => "DICOMweb is a web-based standard for accessing and sharing DICOM data over HTTP, enabling modern web applications to interact with medical imaging data."),
                        Dict("name" => "DICOM Viewer", "url" => "https://www.dicomviewer.com/", "description" => "DICOM Viewer is a software application for viewing and analyzing DICOM medical images, providing tools for diagnosis and research."),
                        Dict("name" => "DICOM Toolkit (DCMTK)", "url" => "https://dicom.offis.de/dcmtk.php.en", "description" => "DCMTK is a collection of libraries and applications for working with DICOM files, offering functionality for parsing, converting, and managing medical imaging data."),
                        Dict("name" => "Understanding and Using DICOM", "url" => "https://pmc.ncbi.nlm.nih.gov/articles/PMC61235/", "description" => "DICOM in Practice: A Comprehensive Guide to DICOM Standards and Implementation in Medical Imaging")
                     ]),
                Dict("key" => "ITK", "name" => "ITK",
                     "url" => "https://itk.org/",
                     "description" => "The Insight Segmentation and Registration Toolkit (ITK) is an open-source software library for medical image processing, segmentation, and registration. It provides a wide range of algorithms and tools for analyzing and manipulating medical imaging data, making it a valuable resource for researchers and clinicians in the field of medical imaging.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Medical Imaging",
                     "related_tools" => [
                        Dict("name" => "SimpleITK", "url" => "https://simpleitk.org/", "description" => "SimpleITK is a simplified layer built on top of ITK that provides an easy-to-use interface for medical image processing tasks."),
                        Dict("name" => "3D Slicer", "url" => "https://www.slicer.org/", "description" => "3D Slicer is an open-source software platform for medical image informatics, image processing, and three-dimensional visualization."),
                        Dict("name" => "Fiji (ImageJ)", "url" => "https://fiji.sc/", "description" => "Fiji is an open-source image processing package based on ImageJ, widely used in the life sciences for analyzing and visualizing medical imaging data.")
                     ]),
                Dict("key" => "Syology", "name" => "Syology",
                     "url" => "https://www.syology.com/",
                     "description" => "Syology is a cutting-edge software platform that leverages quantum computing to enhance medical imaging analysis and diagnostics. By utilizing quantum algorithms, Syology aims to provide faster and more accurate insights from medical imaging data, ultimately improving patient outcomes and advancing healthcare research.",
                     "img" => "https://user-images.githubusercontent.com/6933510/168320384-9c8b1e5c-7a3d-4f2e-9b1c-8a0e5a7c6b9c.png",
                     "category" => "Medical Imaging"),
             ]),
    ],
)
